config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :publications # Borrar except: :create si no funciona
  devise_for :users, except: :create, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/new_user_postulation', to: 'publications#new_user_postulation', as: 'new_user_postulation'
  get '/mispostulaciones', to: 'publications#mypostulations', as: 'user_postulations'
  get '/registrar_usuario', to: 'publications#register_user', as: 'register_user'
  post '/crear_usuario', to: 'publications#create_user', as: 'create_user'
  get '/portal_postulaciones', to: 'pages#index'
  get '/postulaciones_recibidas', to: 'publications#users_postulations', as: 'postulations_received'
  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#index" # Quizás sea necesario redirigir a otra página "home#index" en caso de no estar con sesión iniciada
end

app/models/publication.rb
class Publication < ApplicationRecord
    has_and_belongs_to_many :users
    # has_many :images, as: :imageable  # Previo
    has_many_attached :images   # Exclusivo de la gema activestorage, y necesario para su funcionamiento. Funciona como con el imageable

    # accepts_nested_attributes_for :images 
    # Eliminado, porque activestorage funciona aceptando atributos anidados sin necesidad de esta línea
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!, except: [:index, :show]
  # Dentro  del método authorize_admin, se verifica que el current_user.role sea "admin" o no, y 
  # a partir de ahí permite ejecutar el CRUD de publicaciones y registro de usuarios
  before_action :authorize_admin, only: [:register_user, :create_user, :users_postulations, :new, :create, :update, :destroy]  
  before_action :set_publication, only: %i[ show edit update destroy ]


  # La creación de usuarios está en este mismo controlador, en la sección de ##### Controladores Adicionales #####


  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @Users = User.all
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.users << current_user  # Para permitir agregar el usuario actual a la publicación

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

###########################################################################################################################
                  # Controladores adicionales

  def mypostulations
    @users = User.all
    user_id = current_user.id
    user = User.find(user_id)
    @postulations = user.publications # Me resultó, de alguna manera que aún no determino, pero me manejo mejor con controladores :D
  end

  def users_postulations
    @users = User.all
    @publications = Publication.all
  end

  def register_user
    if current_user.admin?
      @user = User.new
    else
      flash[:alert] = "No tienes permiso para realizar esta acción"
      redirect_to root_path
    end
  end

  def create_user
    if current_user.admin?
      @user = User.new(user_params) # @user será el usuario nuevo, por lo que aquí se establecen los parámetros para que los alamacene temporalmente la página
        if @user.save
          UserMailer.with(user: @user).welcome_email.deliver_now  # Con el ActionMailer, puede enviar correos a usuarios nuevos :3
                                                                  # En este caso, se está enviando al usuario nuevo.

          flash[:alert] = "El usuario se ha registrado exitosamente"
          redirect_to register_user_path
        else
          flash[:alert] = "El usuario no ha podido registrarse"
          render :register_user
        end
    else
      flash[:alert] = "No tienes permiso para realizar esta acción"
      redirect_to root_path
    end
  end

  def authorize_admin
    if current_user.role != "admin"
      flash[:alert] = "No tienes permiso para realizar esta acción"
      redirect_to root_path
    end
  end
  

# Está copiado desde Crazy4Cats, así que lo tengo que adaptar para este proyecto

# before_action :authenticate_user!, except: [:index, :show]  # Para que los no ingresados puedan sólo ver las reacciones, pero no reaccionar

def new_user_postulation
  
  @publication = Publication.find(params[:publication_id]) if params[:publication_id]
  current_user.publications << @publication # Aquí tuve que investigar para añadirle la publicación al usuario como postulación

  # @user = params[:user] # Esta línea estaba generando error, porque en la línea de arriba el usuario está planteado como current_user
  PublicationsMailer.with(user: current_user, publication: @publication).postulate_user.deliver_now

  redirect_to @publication, notice: "Postulación recibida"
end
#########################################################################################################################


  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:name, :description, images: [] )
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :age, :description, :role, images: [])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-2">
    <%= form.label :descripción, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div class="form-group">
    <%= form.label :imágenes %>
    <%= form.file_field :images, multiple: true, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit "Enviar", class: "btn btn-primary text-white mt-3" %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <div class="row">
    <div class="col-xs-6 col-md-6">
      <p class="mb-2">
        <% publication.images.each do |img| %>
          <%= image_tag img, style: "max-width: 32rem", class: "me-2 mb-2" %>
        <% end %>
      </p>
    </div>

    <div class="col-xs-6 col-md-6 pt-2">
      <p>
        <strong><%= publication.name %></strong>        
      </p>
    
      <p>
        <strong>Descripción del puesto:</strong>
        <%= publication.description %>
      </p>
    </div>
  
  </div>
</div>

app/views/publications/edit.html.erb
<h1 class="fw-bold mt-3 mb-4" style="color: #693950;">Editar Publicación</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Ver Publicación", @publication, class: "btn btn-primary text-white my-2" %>
  <% if user_signed_in? && current_user.role == "admin" %>
    <%= button_to "Eliminar Publicación", @publication, method: :delete, class: "btn btn-danger text-white mt-5 mb-2" %> <br>
  <% end %>
  <%= link_to "Volver a las Publicaciones", publications_path, class: "btn btn-info text-white my-2 mt-4" %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="ms-5 mt-2 mb-5 fw-bold" style="color: #693950">Ofertas de puesto</h1>

<% if user_signed_in? && current_user.role == "admin" %> <!-- Primero el signed_in, luego el current_user -->
  <%= link_to "Publicar nueva oferta", new_publication_path, class: "btn btn-warning my-3 fs-5" %>
<% end %>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Entrar a oferta", publication, class: "btn btn-primary text-white my-2" %>
    </p>
    <hr>
  <% end %>
</div>

app/views/publications/mypostulations.html.erb
<!-- Me costó encontrar la forma de hacer esto, pero tiene todo el sentido al crear un análogo a "@" con la variable de abajo
que rescata todos los registros de la tabla intermedia haciendo referencia al usuario por su id.
Aprendí a usar mejor el rails console, así que puedo buscar todo siempre y cuando esté relacionado -->
<% @postulations.each do |postulation| %>
    <%= render postulation %>
    <p>
        <%= link_to "Ver Publicación", postulation %>
    </p>
<% end %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/register_user.html.erb
<%= render 'componentes/formregister' %>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<% if user_signed_in? && @publication.users.include?(current_user) == false && current_user.role == "normal_user" %>
  <%= button_to "Postular", new_user_postulation_path(publication_id: @publication.id), method: :post, class: "btn btn-info text-white mb-2" %>
<% elsif user_signed_in? && @publication.users.include?(current_user) == true && current_user.role != "admin" %>
  <h5>Ya se ha postulado a esta publicación</h5>  
<% end %>

<div>
  <% if user_signed_in? && current_user.role == "admin" %>
  <%= link_to "Editar Publicación", edit_publication_path(@publication), class:"btn btn-success text-white mb-2" %>
  <!-- < %= button_to "Eliminar Publicación", @publication, method: :delete, class: "btn btn-danger text-white mt-5" %> -->
  <% end %>
</div>

<div>
  <%= link_to "Volver a Publicaciones", publications_path, class:"btn btn-info text-white my-3" %>  
</div>

app/views/publications/users_postulations.html.erb
<table class="table table-bordered mt-5 mb-4">
  <thead>
    <tr class="fs-3">
      <th scope="col" style="background-color: #dbadff">Trabajador</th>
      <th scope="col" style="background-color: #dbadff">Descripción laboral</th>
      <th scope="col" style="background-color: #dbadff">Postulación</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <% @users.each do |user| %>
            <%= render 'componentes/postulacion', user: user unless user.role == "admin" %> <!-- Como la "postulación" corresponde a una tabla intermedia entre user y publication, el jefe, quien publica, contará como "postulado", así que con el unless evito referirme a él en la tabla de postulaciones-->
        <% end %>  
      </tr>
  </tbody>
</table>
