config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :publications # Borrar except: :create si no funciona
  devise_for :users, except: :create, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/new_user_postulation', to: 'publications#new_user_postulation', as: 'new_user_postulation'
  get '/mispostulaciones', to: 'publications#mypostulations', as: 'user_postulations'
  get '/registrar_usuario', to: 'publications#register_user', as: 'register_user'
  post '/crear_usuario', to: 'publications#create_user', as: 'create_user'
  get '/portal_postulaciones', to: 'pages#index'
  get '/postulaciones_recibidas', to: 'publications#users_postulations', as: 'postulations_received'
  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#index" # Quizás sea necesario redirigir a otra página "home#index" en caso de no estar con sesión iniciada
end

app/views/componentes/_formregister.html.erb
<div class="container">
    <h2 class="mt-4 mb-2">Registrar usuario</h2>
  
    <%= form_for(@user, url: create_user_path, method: :post) do |f| %>
    <!-- Si aparece el error de undefined_method 'model_name' for, hay que eliminar la palabra 'model:' al inicio de la función -->
      
    <% flash.each do |type, message| %>
    <div class="flash-<%= type %>">
      <h5 style="color: rgb(26, 170, 26)"><%= message %></h5>
    </div>
  <% end %>
  
      <div class="row mt-4">
        <div class="col-md-6">
          <div class="form-group mb-1">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
          </div>
  
          <div class="form-group mb-1">
            <%= f.label :contraseña %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> caracteres como mínimo)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
          </div>
  
          <div class="form-group mb-1">
            <%= f.label :confirmar_contraseña %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
          </div>
  
          <div class="form-group mb-1">
            <%= f.label :nombre %><br />
            <%= f.text_field :name, autocomplete: "Nombre de usuario", class: "form-control" %>
          </div>
        </div>
  
        <div class="col-md-6">
          <div class="form-group mb-1">
            <p class="fw-bold">Foto de perfil:</p>
            <%= f.file_field :images, multiple: true, class: 'form-control' %>
          </div>
        </div>
      </div>
  
      <div class="actions">
        <%= f.submit "Registrar", class: "btn btn-primary mt-3" %>
      </div>
    <% end %>
  
    <!-- < %= render "devise/shared/links" %> --> <!-- Esta línea actúa de parte de los controladores de devise, por lo que se elimina -->
  </div>
  

app/views/componentes/_navbar.html.erb
<nav class="navbar navbar-expand-lg", style= "color: #d6c1bd; background-color: #693950">
    <div class="container-fluid">
      <!-- image_tag de abajo en caso de querer agregar una imagen -->
      <!-- < %= image_tag "https://img-fotki.yandex.ru/get/60380/200418627.158/0_16d9e0_8298de2a_orig.png", style: "max-width: 5rem;" %> --> 
      <%= link_to "Portal Postulaciones", root_path, class: "navbar-brand fs-2 btn fw-bold", style: "color: #30D5C8;" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <%= link_to 'Publicaciones', publications_path, class: "btn text-info" %>
            <% if user_signed_in? %>

                <!-- Esta línea será para el contenido al cual puede acceder el administrador -->

                <% if current_user.role == "admin" %> 
                    <!-- < %= link_to "Mis Publicaciones", publications_path, class: "btn text-info" %> -->
                    <%= link_to "Postulaciones recibidas", postulations_received_path, class: "nav-link active btn text-info" %>
                    <%= link_to "Registrar Usuario", register_user_path, class: "nav-link active btn text-info" %>
                <% end %>

                <% if current_user.role == "normal_user" %>
                  <%= link_to "Mis postulaciones", user_postulations_path, class: "nav-link active btn text-info" %>
                <% end %>


                <% if current_user.images.present? %> <!-- Cuidado con el nombre del atributo que se refiere a foto -->
                    <%= image_tag current_user.images.last, style: "height: 2rem; width: 2rem", class:"rounded-circle" %>
                <% end %>

                <%= button_to "#{current_user.email}", root_path, class:"nav-link disabled btn btn-primary-outline", style: "color: #37FD12;", disable: true %>
                <%= link_to "Editar Perfil", edit_user_registration_path, class: "btn text-info" %>
                <%= button_to 'Cerrar Sesión', destroy_user_session_path, class: "nav-link active btn text-danger", method: :delete %>
            <% else %>
              <%= link_to "Inicio", publications_path, class: "nav-link active btn text-info" %>
              <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link active btn text-info" %>
            <% end %>
        </div>
      </div>
    </div>
  </nav>

app/views/componentes/_postulacion.html.erb
<tr id="<%= dom_id user %>">   <!-- IMPORTANTE DEFINIR EL ID DEL USUARIO -->
    
        <td style="background-color: #FFF0F0;"><%= user.name %></td>
        <td style="background-color: #FFF0F0;"><%= user.description %></td>
        <td style="background-color: #FFF0F0;">
            <% user.publications.each do |publication| %>
                <li><%= link_to "#{ publication.name }", publication %></li> <!-- Probar a poner un link to -->
            <% end %> 
        </td>    
</tr>